### ISSUE TITLE
crashed when a bounty mod spawned because of monster spawner? (maybe??)

### ISSUE THREAD

**Issue by slovinsqui** [spoorn/SpoornBountyMobs#12]
I was playing mc 1.19.2, when entering a dungeon from the Dungeons Now Loading mod, the game crashed.
Not enough crashes (mod) flagged Bounty mobs.
When cheking the crash report, the game says something about mob spawners

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-09-07 17:50:38
Description: Ticking block entity

java.lang.NoSuchFieldError: field_11735
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.9)
	at org.spoorn.spoornbountymobs.entity.SpoornBountyEntityRegistry.lambda$registerStartTrackingCallback$3(SpoornBountyEntityRegistry.java:229)
	at net.fabricmc.fabric.api.networking.v1.EntityTrackingEvents.lambda$static$0(EntityTrackingEvents.java:36)
	at net.minecraft.server.network.EntityTrackerEntry.handler$dce000$onStartTracking(EntityTrackerEntry:1040)
	at net.minecraft.server.network.EntityTrackerEntry.startTracking(EntityTrackerEntry)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage$EntityTracker.updateTrackedStatus(ThreadedAnvilChunkStorage:1416)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage$EntityTracker.updateTrackedStatus(ThreadedAnvilChunkStorage:1442)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.loadEntity(ThreadedAnvilChunkStorage:1198)
	at net.minecraft.server.world.ServerChunkManager.loadEntity(ServerChunkManager:477)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1560)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1538)
	at net.minecraft.server.world.ServerEntityManager.startTracking(ServerEntityManager:217)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:187)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:168)
	at net.minecraft.server.world.ServerWorld.addEntity(ServerWorld:865)
	at net.minecraft.server.world.ServerWorld.spawnEntity(ServerWorld:816)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.world.ServerWorldAccess.spawnEntityAndPassengers(ServerWorldAccess:11)
	at net.minecraft.server.world.ServerWorld.spawnNewEntityAndPassengers(ServerWorld:873)
	at net.minecraft.world.MobSpawnerLogic.serverTick(MobSpawnerLogic:157)
	at net.minecraft.block.entity.MobSpawnerBlockEntity.serverTick(MobSpawnerBlockEntity:54)
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk:660)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk:714)
	at net.minecraft.world.World.tickBlockEntities(World:456)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:376)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spoorn.spoornbountymobs.entity.SpoornBountyEntityRegistry.lambda$registerStartTrackingCallback$3(SpoornBountyEntityRegistry.java:229)
	at net.fabricmc.fabric.api.networking.v1.EntityTrackingEvents.lambda$static$0(EntityTrackingEvents.java:36)
	at net.minecraft.class_3231.handler$dce000$onStartTracking(class_3231.java:1040)
	at net.minecraft.class_3231.method_18760(class_3231.java)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1416)
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1442)
	at net.minecraft.class_3898.method_18701(class_3898.java:1198)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1560)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1538)
	at net.minecraft.class_5579.method_31847(class_5579.java:217)
	at net.minecraft.class_5579.method_31820(class_5579.java:187)
	at net.minecraft.class_5579.method_31818(class_5579.java:168)
	at net.minecraft.class_3218.method_14175(class_3218.java:865)
	at net.minecraft.class_3218.method_8649(class_3218.java:816)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5425.method_30771(class_5425.java:11)
	at net.minecraft.class_3218.method_30736(class_3218.java:873)
	at net.minecraft.class_1917.method_31588(class_1917.java:157)
	at net.minecraft.class_2636.method_31697(class_2636.java:54)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: minecraft:mob_spawner // net.minecraft.class_2636
	Block: Block{minecraft:spawner}
	Block location: World: (255,93,-399), Section: (at 15,13,1 in 15,5,-25; chunk contains blocks 240,-64,-400 to 255,319,-385), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{minecraft:spawner}
	Block location: World: (255,93,-399), Section: (at 15,13,1 in 15,5,-25; chunk contains blocks 240,-64,-400 to 255,319,-385), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block Entity NBT: {Delay:0s,MaxNearbyEntities:6s,MaxSpawnDelay:800s,MinSpawnDelay:200s,RequiredPlayerRange:16s,SpawnCount:4s,SpawnData:{entity:{id:"minecraft:zombie"}},SpawnGuardian:0b,SpawnPotentials:[{data:{entity:{id:"minecraft:zombie"}},weight:1}],SpawnRange:4s}
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Slovinsqui'/8915, l='ServerLevel[New World]', x=259.41, y=92.00, z=-402.74]]
	Chunk stats: 4329
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,94,0), Section: (at 0,14,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3457 game time, 3457 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 139653 (now: false), thunder time: 125568 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 816627328 bytes (778 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25564.39
	Virtual memory used (MB): 14428.46
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 13.38
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.6
		adventurez: AdventureZ 1.4.16
		airhop: Air Hop 4.2.1
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		another_furniture: Another Furniture 2.0.3-1.19.2
		architectury: Architectury 6.2.43
		attributefix: AttributeFix 17.1.2
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.0
		beenfo: Beenfo 1.19.1-fabric0.58.5-1.3.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		betteradvancements: Better Advancements 0.2.2.142
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.1.0
		betterf3: BetterF3 1.3.2
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		bettersafebed: BetterSafeBed 4
		bettersleeping: BetterSleeping 0.6.1+1.19
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		bettertaskbar: Better Taskbar 1.5
		betterthirdperson: Better Third Person 1.8.1
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		boatiview: Boat Item View Fabric 0.0.4
		bookshelf: Bookshelf 16.1.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bowinfinityfix: Bow Infinity Fix 2.5.0
		brb: Better Recipe Book 1.6.0
		bsvsb: Better Sodium Video Settings Button 3.0.2
		campchair: Camp Chair 1.0.2
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		cenchants: Combat Enchants 2.14.2
		chalk: Chalk 2.1.0+1.19
		charm: Charm 4.2.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		charmonium: Charmonium 4.1.0
		chat_heads: Chat Heads 0.7.1
		cleancut: CleanCut 1.19.2-5.1-fabric
		cleardespawn: Clear Despawn 1.1.9
		clickadv: Clickable Advancements Mod 2.9
		collective-fabric: Collective (Fabric) 4.52
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.2+mc.1.19
		colouredtooltips: ColouredTooltips 18.1.3
		completeconfig: CompleteConfig 2.0.0
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		concreteconversion: Concrete Conversion 6.1.0.0
		connectivity: Connectivity Mod 1.19-3.3
		controlling: Controlling For Fabric 10.0+6
		copper_pipe: Simple Copper Pipes 1.11-b5
		cr-arrows-info: Arrows Info 1.2.1+1.19
		creativecore: CreativeCore (Fabric) 2.7.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1
		cull-less-leaves: Cull Less Leaves 1.0.5
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			conditional-mixin: conditional mixin 0.3.0
		customizableelytra: Customizable Elytra 1.6.2-1.19
		customlan: Custom LAN 1.19.1-v2.2.0
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.6.0
		deepslatecutting: Deepslate Cutting 1.4.0
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		duckling: Duckling 2.0.7
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dungeon_now_loading: dungeon-now-loading-17-1 1.0.0
		dusk: Dusk Mod 1.19.1-2.2
		dynamiccrosshair: Dynamic Crosshair 3.5.1+1.19
		dynamiccrosshaircompat: Dynamic Crosshair Compat 1.4+1.19
		dynamicfps: Dynamic FPS 2.2.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		easymagic: Easy Magic 4.3.2
		eatinganimationid: Eating Animation 1.9
		ecologics: Ecologics 2.1.9
		economical_villager_trading: Economical Villager Trading 1.2.8
		effective: Effective 1.2.2
		elementa: Elementa 544
		elytra_physics: ElytraPhysics 1.1
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchant_the_rainbow: Enchant the Rainbow 1.1.0
		enchdesc: EnchantmentDescriptions 13.0.1
		endrem: End Remastered 5.1.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedcelestials: Enhanced Celestials 2.1.0.1
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		essential: Essential 4804+g97db1f45b
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		essential-dependencies: Essential Dependencies 0
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		farmersdelight: Farmer's Delight 1.19-1.3.3
		farsighted-mobs: Farsighted Mobs 1.1-1.18-1.19
		ferritecore: FerriteCore 4.2.1
		fireworkfrenzy: Firework Frenzy 1.10
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fwaystones: Fabric Waystones 3.0.3+mc1.19.2
			pinlib: PinLib 0.1.3+1.19
		geckolib3: Geckolib 3.1.18
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		hardcorerevival: Hardcore Revival 9.0.0
		healthindicators: PlayerHealthIndicators 1.0.1
		healthoverlay: Health Overlay 7.1.1
		highlighter: Highlighter 1.1.4
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.8
		immersive_paintings: Immersive Paintings 0.2.0+1.19.2
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		impaled: Impaled 1.1.4
		incantationem: Incantationem 1.1.4+1.19
		indium: Indium 1.0.9+mc1.19.2
		indypets: IndyPets - Independent Pets 1.1.0-1.19.2
		inventoryhotswap: Inventory Hotswap 1.3.0
		iris: Iris 1.2.8
			org_anarres_jcpp: jcpp 1.4.14
		itemborders: Item Borders 1.1.6
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		just_end_anchor: Just An End Anchor 1.0.2
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.2.6
		letsleepingdogslie: Let Sleeping Dogs Lie 1.1.0
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.8.3
		lootr: Lootr 0.4.22.61
		magick: Magick: Potions and Pearls 1.3.2
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.2-1.19
		mambience: MAmbience 5.2.0+1.19
		maptooltip: Map Tooltip 2.0.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19.2
		moderate-loading-screen: Mod-erate Loading Screen 1.1.3+1.19
		modid: Creatures Of The Snow 2.4.2+1.19.2
		modmenu: Mod Menu 4.0.6
		morebannerfeatures: More Banner Features 1.1.3
		moreculling: More Culling 1.19.1-0.10.0
			cloth-config: Cloth Config v6 7.0.74
				cloth-basic-math: cloth-basic-math 0.6.1
		mousewheelie: Mouse Wheelie 1.10.2+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		musicbox: Music Box v1.0.1+1.19.2
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.0
			com_github_walkyst_lavaplayer-fork: lavaplayer-fork 1.3.97
			com_sedmelluq_lava-common: lava-common 1.1.2
			com_sedmelluq_lavaplayer-natives: lavaplayer-natives 1.3.14
			org_apache_httpcomponents_httpclient: httpclient 4.5.13
			org_apache_httpcomponents_httpcore: httpcore 4.4.14
		naturalist: Naturalist 2.1.1
		netherportalfix: NetherPortalFix 10.0.0
		nodami: No Damage Immunity(NoDamI) Reload Mod 1.0.0
		nofade: No Fade 1.18-2.0.1
		notenoughanimations: NotEnoughAnimations 1.6.1
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		npcvariety: NPC Variety 2.2.2
		org_jetbrains_annotations: annotations 13.0
		patchouli: Patchouli 1.19.2-76-FABRIC
		philips_ruins__fabric: Philips ruins 1.19.2 fabric 1.3
		phosphor: Phosphor 0.8.1
		pling: Pling 1.5.0
		polaroidcamera: PolaroidCamera 1.3.0
		polylib: PolyLib 1900.0.2-build.27
		polymorph: Polymorph 0.45.0+1.19.2
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		projectsavethepets: Project: Save the Pets! 3.2.0+2022.e000b2a529.fabric
		puzzleslib: Puzzles Lib 4.3.1
		rad: Reload Audio Driver 1.0.2
		raised: Raised 1.1.2
		rpgdifficulty: Rpg Difficulty 1.2.1
		scout: Scout 1.1.1
		serverpause: Multiplayer Server Pause 1.1.0
		sgod: Save Gear on Death 2.0.0-1.19
		shouldersurfing: Shoulder Surfing Reloaded 2.2.12
		showmeyourskin: Show Me Your Skin! 1.3.3+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.1.2+1.19.2
		skinlayers: 3d Skin Layers 1.5.1-mc1.19.1
		skylorlib: SkyLib 1.5.1
		sleepwarp: SleepWarp 1.2.0+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.12
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		splatus_ultris: Ultris: Boss Expansion 5.6.4
		spoornbountymobs: SpoornBountyMobs 2.7.4-1.19
			org_apache_commons_commons-math3: commons-math3 3.3
		spyglass-improvements: Spyglass Improvements 1.3+mc1.19+fabric
		status-effect-bars: Status Effect Bars 1.0.1
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b1
		structory: Structory 1.0.1
		terrablender: TerraBlender 2.0.1.127
		third_person_maps: Third Person Maps 1.4.0
		toolstats: ToolStats 12.0.2
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tooltiprareness: Tooltip Rareness 1.0.6
		trinkets: Trinkets 3.4.0
		universalcraft: UniversalCraft 225
		uteamcore: U Team Core 4.1.0.6
		vigilance: Vigilance 252
		visuality: Visuality 0.5.1
		voicechat: Simple Voice Chat 1.19.2-2.3.9
		vorpal-enchantment: Vorpal Enchantment 3.0.3
		wandering_collector: Wandering Collector 1.1.3+mc1.19
		waterdripsound: Drip Sounds 1.19-0.3.0
		weaponmaster: YDM's Weapon Master 3.0.0 
		wilderwild: Wilder Wild 1.0.6-Fabric+1.19.2
			mm: Manningham Mills 2.3
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		yet-another-config-lib: YetAnotherConfigLib 0.1.2
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Slovinsqui'/8915, l='ServerLevel[New World]', x=259.41, y=92.00, z=-402.74]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.9-1.19.2
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 2
	Suspected Mods: Fabric Networking API (v1) (fabric-networking-api-v1), SpoornB

**Comment by slovinsqui** [comment]
oh apparently fabric networking API is also suspected

another crash happend outside the dungeon, no spawners involved


[latest.log](https://github.com/spoorn/SpoornBountyMobs/files/9522714/latest.log)

[2022-09-07-6.log.gz](https://github.com/spoorn/SpoornBountyMobs/files/9522717/2022-09-07-6.log.gz)

**Comment by spoorn** [comment]
You need the later version of SpoornBountyMobs.  2.7.4-1.19 only supported <=1.19 but 1.19.1 introduced some changes to the chat broadcasting system
