### ISSUE TITLE
Spoorn Bounty Mobs crashes with ClassNotFoundException

### ISSUE THREAD

**Issue by Derpford** [spoorn/SpoornBountyMobs#2]
This appears to be related to AutoConfig, based on the trace.

Crash report:
https://pastebin.com/HEghRFHe

**Comment by Derpford** [comment]
On closer inspection, it appears CurseForge does not do version checking for specific versions of 1.16--I have several mods that are set to use their 1.16.4 versions even though I'm running 1.16.3.

**Comment by Derpford** [comment]
On further investigation, every file for Spoorn Bounty Mobs is marked as compatible with literally every version of 1.16 that Fabric supports.

What the fuck?

**Comment by spoorn** [comment]
Please reopen if this issue persists.  The mod should be compatible with all 1.16 versions.  The error looks like your Cloth Config might be outdated
