### ISSUE TITLE
Stop at world loading

### ISSUE THREAD

**Issue by Paw-El-Cow** [spoorn/SpoornBountyMobs#3]
New world, old world - doesn't matter. No crash - no logs.
![Снимок](https://user-images.githubusercontent.com/89390891/130441199-66a9f2bd-8777-4ce8-b615-60e5f07fc3a2.PNG)

System and mods info generated by crashing another mod (not in the list):
[Новый текстовый документ.txt](https://github.com/spoorn/SpoornBountyMobs/files/7031570/default.txt)

**Comment by spoorn** [comment]
haven't seen this issue happen for anyone else.  Please reopen if it persists in the latest version with only this mod installed
