### ISSUE TITLE
Adding NBT tags to items in loot table

### ISSUE THREAD

**Issue by ThinkWithPbody** [spoorn/SpoornBountyMobs#5]
I want to use spoornbountymobs along with predefined loot bags from modular loot crates, however this requires the use of NBT tags, for example tag: {LootTable: "minecraft:chests/stronghold_corridor"}. Is it possible that I can add the NBT tag to my config file? 

`"drops": [
		   	{
		   		"entityId": ".*", 
		   		"dropChance": 1, 
		   		"rolls": 1, 
		   		"items": [
		   			{
		   				"item": "lootcrates:common_loot_bag",
		   				"weight": 1
		   			},
		   		]
		   	}
]`

**Comment by spoorn** [comment]
No this isn't supported at the moment.  I'm not sure if it's worth adding either as customizing the NBT data for particular items like this feels pretty hacky to me and error prone. 

I could look into adding support for particular loot tables though, which might be better anyways for your use case

**Comment by ThinkWithPbody** [comment]
I understand. For now I can just hand out loot chests with NBT data to players manually, and add crate keys as a loot drop from mobs, so no worries about adding features. Thanks!

**Comment by spoorn** [comment]
This is now supported in 1.18+ and 1.19+
