### ISSUE TITLE
"Exception ticking world" Crash Report

### ISSUE THREAD

**Issue by Wpgradford** [spoorn/SpoornBountyMobs#6]
I'm not sure what could've caused this, I was just putting stuff into a furnace and I crashed. Here's the full crash report:
[crash-2022-04-03_12.45.28-server.txt](https://github.com/spoorn/SpoornBountyMobs/files/8404305/crash-2022-04-03_12.45.28-server.txt)

**Comment by spoorn** [comment]
Could you check your config at `config/spoornbountymobs.json5`?  What is `playerBountyHunterLevelIntervals` set to?  If it's 0, try changing it to another number

**Comment by Wpgradford** [comment]
Ohhh that makes sense, I did set it to 0

**Comment by spoorn** [comment]
The Interval can't be 0.  I'll add a check to error out early with an error message for the user when this happens
