### ISSUE TITLE
Chat announcements

### ISSUE THREAD

**Issue by SilverNinetails** [spoorn/SpoornBountyMobs#9]
I've been playing on a server with friends and it seems only certain people can see the bounty mob announcement in chat, others just seem to see their name and we can't figure out whats different between the people who can see the full announcement ans those who only see the user name announced in chat, I've been looking around to see if theres a fix or setting but haven't found one yet

**Comment by spoorn** [comment]
Are the other people on different locales/lang?  There's only en_us translation

**Comment by SilverNinetails** [comment]
Were all in the US and all use the English setting for the game

**Comment by spoorn** [comment]
What versions of Minecraft, Fabric, and SpoornBountyMobs are you all using?

I had made a change in a recent version where I updated the key used for the broadcast message to properly translate across client-server, and if the client is on a different version, it could cause it to only display the user name and not translate the rest

**Comment by SilverNinetails** [comment]
Were playing on the darkrpg mod pack for fabric on 1.18.1, it's weird because only some of us get this issue, we've looked at eachothers settings and they seem to be the same

**Comment by spoorn** [comment]
Let me know if this issue persists on later versions
